
spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/academia
      username: postgres
      password: ttdsmfm9854
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
        jdbc:
          lob:
            non_contextual_creation: true
      properties:
        hibernate.format_sql: true
